### ISSUE TITLE
pcunner does not start with trailing empty line in commands.txt

### ISSUE THREAD

**Issue by jalbstmeijer** [maartenq/pcrunner#4]
Stopping pcrunner:                                         [FAILED]
Starting pcrunner: Traceback (most recent call last):
  File "/usr/bin/pcrunner", line 9, in <module>
    load_entry_point('pcrunner==0.1.0', 'console_scripts', 'pcrunner')()
  File "/usr/lib/python2.6/site-packages/pcrunner/main.py", line 910, in main
    pcrunner = PassiveCheckRunner(**pcrunner_args)
  File "/usr/lib/python2.6/site-packages/pcrunner/main.py", line 228, in **init**
    configuration.read_check_commands(self.command_file)
  File "/usr/lib/python2.6/site-packages/pcrunner/configuration.py", line 191, in read_check_commands
    return read_check_commands_txt(command_file_name)
  File "/usr/lib/python2.6/site-packages/pcrunner/configuration.py", line 170, in read_check_commands_txt
    } for y in (x.split('|') for x in commands.splitlines())
IndexError: list index out of range

**Comment by maartenq** [comment]
fixed in 0.2.6
